# Generated by Django 5.1.2 on 2024-11-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istreetapp', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(default='Enter your number', max_length=10),
        ),
    ]
