# Generated by Django 5.1.2 on 2024-11-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istreetapp', '0004_alter_payment_payment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='/media/images/iPhone6.webp', null=True, upload_to='images/'),
        ),
    ]
