# Generated by Django 5.1.2 on 2024-11-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istreetapp', '0006_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='\\media\\images\\iPhone6.webp', null=True, upload_to='images/'),
        ),
    ]
