# Generated by Django 5.1.2 on 2024-11-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istreetapp', '0008_alter_item_image_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
    ]
