# Generated by Django 5.1.2 on 2024-11-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istreetapp', '0009_remove_testimonial_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
