# Generated by Django 5.1.2 on 2024-11-29 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istreetapp', '0010_alter_testimonial_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='istreetapp.payment'),
        ),
    ]
