# Generated by Django 5.1.2 on 2024-11-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istreetapp', '0013_order_refund_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
    ]
