# Generated by Django 5.1.2 on 2024-11-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istreetapp', '0016_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
